// Generated by CodiumAI

describe('FormInput', () => {

});

    // Tests that the FormInput component renders a label and an input element
    it('should render a label and an input element', () => {
        const wrapper = shallow(<FormInput label='Test Label' />);
        expect(wrapper.find('label').text()).toEqual('Test Label');
        expect(wrapper.find('input')).toHaveLength(1);
    });

